[package]
name = "mta-indicator"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
pulse_nyct = { git = "https://github.com/ofrighil/pulse" }
rpi-led-matrix = "0.4"
